
export const PROHIBITED_TERMS: Record<string, string> = {
    'win feature': 'play feature',
    'pay out': 'win / won',
    'paid out': 'win',
    'stake': 'play amount',
    'pays out': 'won',
    'betting': 'play / playing',
    'total bet': 'total play',
    'bet': 'play',
    'bets': 'plays',
    'cash': 'coins',
    'payer': 'winner',
    'pay': 'win',
    'pays': 'wins',
    'paid': 'won',
    'money': 'coins',
    'buy': 'play',
    'bought': 'instantly triggered',
    'purchase': 'play',
    'at the cost of': 'for',
    'rebet': 'respin',
    'cost of': 'can be played for',
    'credit': 'coins',
    'buy bonus': 'get bonus',
    'gamble': 'play',
    'wager': 'play',
    'deposit': 'get coins',
    'withdraw': 'redeem',
    'bonus buy': 'bonus / feature',
    'be awarded to player\'s accounts': 'appear in player\'s accounts',
    'place your bets': 'come and play / join in the game',
    'bet/s': 'play/s',
};
